server:
  port: 8087
  tomcat:
    max-swallow-size: 100MB
    max-http-header-size: 40960
    connection-timeout: 100s
    max-threads: 1000
    # 等待队列长度，默认100
    accept-count: 1000
    max-connections: 20000
    # 最小工作空闲线程数，默认10, 适当增大一些，以便应对突然增长的访问量
    min-spare-threads: 100
  ssl: #ssl配置
    enabled: true  # 默认为true
    #key-alias: alias-key # 别名(可以不进行配置)
    # 保存SSL证书的秘钥库的路径
    key-store: C:\Users\Administrator\Desktop\ssl\zeantong.com.jks
    key-store-password: zeantong.com09b6a2d8 #证书密码
    key-store-type: JKS    #证书类型



spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/tickets?useUnicode=true&useSSL=false&allowLoadLocalInfile=false&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&connectTimeout=500000&socketTimeout=500000
    #url: jdbc:mysql://127.0.0.1:3306/tickets?useUnicode=true&useSSL=false&allowLoadLocalInfile=false&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&connectTimeout=500000&socketTimeout=500000
    username: mysqld
    password: Aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 10240
      min-idle: 5120
  jpa:
    show-sql: true
  jackson:
    date-format: yyy-MM-dd
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      # 不限制文件大小
      max-file-size: -1
      # 不限制请求体大小
      max-request-size: -1
      # 临时IO目录
      location: "${java.io.tmpdir}"
      # 不延迟解析
      resolve-lazily: false
      # 超过1Mb，就IO到临时目录
      file-size-threshold: 1MB
    connection-timeout: 12000



mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    #mybatis数据库字段内容为空时，返回该字段

# 日志配置
logging:
  level:
    com.tickets: info
    org.springframework: warn

# 设置堆外内存
tomcat:
  max-connections: 5120

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: platform
      paths-to-match: '/**'
      packages-to-scan: com.tickets.controller

knife4j:
  enable: true
  setting:
    language: zh_cn