server:
  port: 8080
  tomcat:
    max-swallow-size: 100MB
#  ssl: #ssl配置
#    enabled: true  # 默认为true
#    #key-alias: alias-key # 别名(可以不进行配置)
#    # 保存SSL证书的秘钥库的路径
#    key-store: C:\Users\Administrator\Desktop\target\ssl\zeantong.com.jks
#    key-store-password: zeantong.com09b6a2d8 #证书密码
#    key-store-type: JKS    #证书类型



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tickets?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: mysqld
    password: Aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
  jackson:
    date-format: yyy-MM-dd
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.tickets: info
    org.springframework: warn

config:
  arcface-sdk:
    sdk-lib-path: C:\Users\11583\Desktop\ticket-project\lib\WIN64
    app-id: 6GkHezpaFzQb6niUHYo9ZoR4XZEUqd7h5TnUfp77iRx4
    sdk-key: 4J7oBSN3frcLvoAv3CvXnz4LqafKrModsVg77s4HVRrG
    detect-pool-size: 5
    compare-pool-size: 5

